=head1 NQ-NQP-rx - Not Quiet NQP-rx

NQP is Copyright (C) 2009 by The Perl Foundation.  See F<LICENSE>
for licensing details.

This project is mostly a learning exercise for me to try to learn more about compilers. However, as a long term goal, it would be nice to develop a bison or yacc like program that can be used to develop a parser for a dynamic grammar.

=head2 Requirements

This project requires the llvm, bison, flex, and cmake. Currently, I am using:

llvm: version 2.7 
bison: version 2.5.35
flex: version 2.4.1
cmake: version 2.8.1

This may work with other versions of bison, flex or cmake, but because of the tight integration with the llvm, you will need the same version I am using. See the llvm website for more details on building the llvm.

=head2 Building

CMake takes care of all of the configuratoins, so simply run: 

cmake . 
make


